
    var pm_keywords = [
        ".net",
    "a/b testing",
    "acceptance criteria",
    "acquisition",
    "adobe powerbi",
    "advertising proposals",
    "agile",
    "aha",
    "analytical",
    "analytical skills",
    "android",
    "angular",
    "api",
    "application developer",
    "asana",
    "aws",
    "azure",
    "b2b",
    "b2b technology",
    "b2c",
    "b2g",
    "backend",
    "backlog",
    "balsamiq",
    "basecamp",
    "batch data",
    "bootstrap",
    "brand management",
    "breakdown complex problems",
    "business administration",
    "business case",
    "chart.js",
    "cloud data services",
    "cloud infrastructure",
    "communication skills",
    "competitive analysis",
    "complex systems",
    "confluence",
    "consulting",
    "consumer",
    "consumer products",
    "conversion",
    "cross-functional",
    "css",
    "customer analysis",
    "customer empathy",
    "customer journey",
    "customer needs",
    "customer success",
    "customer surveys",
    "customer value",
    "data",
    "data analytics",
    "data visualization",
    "data-driven",
    "database",
    "decision making",
    "design",
    "detail-oriented",
    "developer relations",
    "digital marketing",
    "discovery",
    "distributed products",
    "distributed system",
    "distribution strategy",
    "django",
    "drupal",
    "early employee",
    "early stage startups",
    "end-to-end",
    "engineer",
    "enterprise",
    "enterprise saas",
    "enterprise software",
    "entrepreneurial",
    "entrepreneurship",
    "evaluate risks",
    "execution",
    "extreme programming",
    "fast-growing",
    "fast-paced",
    "feedback",
    "finance",
    "financial planning",
    "forecasting",
    "founder",
    "funnel",
    "gaming",
    "gant chart",
    "go to market",
    "go-to-market",
    "go-to-market strategy",
    "goal oriented",
    "google analytics",
    "graphql",
    "growth",
    "gtm",
    "gtm strategy",
    "heap analytics",
    "high availability",
    "html",
    "html5 app",
    "ide",
    "industry trends",
    "integrations",
    "interviews",
    "inventory control",
    "investment banking",
    "invision",
    "ios",
    "it operations",
    "java",
    "java enterprise edition",
    "javascript",
    "jira",
    "jquery",
    "kissmetrics",
    "lean",
    "lean startup",
    "legal",
    "machine learning",
    "market",
    "market analysis",
    "market research",
    "market trends",
    "merchandising",
    "metadata management",
    "minimal viable product",
    "mixpanel",
    "mobile app",
    "mobile web",
    "mockups",
    "mql",
    "mvp",
    "mysql",
    "node",
    "operating systems",
    "ops",
    "optimizely",
    "organizational ability",
    "organizational skills",
    "performance",
    "php",
    "platform services",
    "prds",
    "pricing",
    "pricing frameworks",
    "problem",
    "product",
    "product design",
    "product ecosystem",
    "product implementation",
    "product launch",
    "product lifecycle",
    "product management",
    "product manager",
    "product marketing",
    "product requirement document",
    "product specs",
    "product vision",
    "python",
    "qa",
    "quality assurance",
    "quantitative",
    "quantitative model",
    "query language",
    "r&d",
    "rails",
    "react",
    "reactnative",
    "realm mobile database",
    "regulatory",
    "release",
    "reliability",
    "requirements analysis",
    "requirements gathering",
    "research",
    "research and development",
    "resolve dependencies",
    "revenue growth",
    "roadmap",
    "roadmunk",
    "ruby",
    "rust",
    "saas",
    "sales",
    "sales and marketing",
    "salesforce",
    "scala",
    "scalability",
    "scope",
    "scrum",
    "sdlc",
    "search engine optimization",
    "search processing",
    "segments",
    "self-motivate",
    "self-starter",
    "sell your ideas",
    "seo",
    "ship",
    "sketch",
    "slack",
    "software",
    "software development",
    "software development lifecycle",
    "software engineering",
    "specification",
    "sprint",
    "spss",
    "sql",
    "sre",
    "stakeholders",
    "startup",
    "status",
    "strategy",
    "stream data",
    "success metrics",
    "swift",
    "swot analysis",
    "tableau",
    "technical",
    "technical architecture",
    "technical documentation",
    "testing",
    "tradeshows",
    "trello",
    "triage issues",
    "typescript",
    "ui",
    "usability",
    "use cases",
    "user centric",
    "user empathy",
    "user experience",
    "user persona",
    "user requirements",
    "user research",
    "user stories",
    "user test",
    "user-centered",
    "user-centered design",
    "ux/ui",
    "validate",
    "venture capital",
    "verbal communication skills",
    "vision",
    "vue.js",
    "wireframing",
    "work collaboratively",
    "written",

    ]

    export { pm_keywords }
    