var pm_marketing_keywords = 
            
    [    ".net",
    "a/b email test",
    "a/b test",
    "acceptance criteria",
    "account optimization",
    "accounting",
    "acquisition",
    "ad-hoc",
    "adobe creative cloud",
    "adobe creative suite",
    "adobe illustrator",
    "adobe photoshop",
    "adobe powerbi",
    "adobe suite",
    "adtech",
    "advertising campaign management",
    "advertising campaigns",
    "advertising proposals",
    "advertising strategy",
    "agile",
    "aha",
    "analytical",
    "analytical skills",
    "android",
    "angular",
    "api",
    "application developer",
    "art direction",
    "asana",
    "automation tools",
    "autopilot",
    "aws",
    "azure",
    "azuredb",
    "b2b",
    "b2b technology",
    "b2c",
    "b2g",
    "babel",
    "backend",
    "backlog",
    "balsamiq",
    "base sas",
    "basecamp",
    "batch data",
    "bing",
    "bing ads",
    "bootstrap",
    "brand management",
    "breakdown complex problems",
    "brightedge",
    "browserify",
    "btravis ci",
    "buffer",
    "business administration",
    "business case",
    "business reports",
    "business strategy",
    "campaign creation",
    "campaign management",
    "campaign plans",
    "canva",
    "chart.js",
    "client acquisition",
    "cloud data services",
    "cloud infrastructure",
    "clustering",
    "cms",
    "commercial operations",
    "communication skills",
    "communications",
    "competitive analysis",
    "complex systems",
    "conflict resolution",
    "confluence",
    "conjoint",
    "consulting",
    "consumer",
    "consumer decision frameworks",
    "consumer products",
    "consumer psychology",
    "content development",
    "content marketing",
    "conversion",
    "copywriting",
    "create report",
    "creative production",
    "critical analysis",
    "critical thinking",
    "crm",
    "cross-functional",
    "cross-sell path",
    "css",
    "customer analysis",
    "customer empathy",
    "customer engagement",
    "customer journey",
    "customer needs",
    "customer oriented",
    "customer success",
    "customer surveys",
    "customer value",
    "customer-facing marketing tools",
    "data",
    "data analysis",
    "data analytics",
    "data science",
    "data studio",
    "data visualization",
    "data-driven",
    "database",
    "decision making",
    "decision trees",
    "decision-making",
    "demand generation",
    "design",
    "detail-oriented",
    "developer relations",
    "digital campaigns",
    "digital marketing",
    "digital-minded",
    "direct mail marketing",
    "discovery",
    "distributed products",
    "distributed system",
    "distribution channels",
    "distribution strategy",
    "django",
    "docusign",
    "domo",
    "doubleclick",
    "drupal",
    "early employee",
    "early stage startups",
    "eloqua",
    "email campaigns",
    "email marketing",
    "end-to-end",
    "engineer",
    "enterprise",
    "enterprise saas",
    "enterprise software",
    "entrepreneurial",
    "entrepreneurship",
    "etl",
    "evaluate risks",
    "event budget tracker",
    "event marketing",
    "evergreen campaigns",
    "excel",
    "excel / spreadsheet",
    "execution",
    "experimental test",
    "extreme programming",
    "facebook",
    "facebook ads",
    "facebook ads manager",
    "fast-growing",
    "fast-paced",
    "feedback",
    "finance",
    "financial planning",
    "firebase",
    "flexbox",
    "forecasting",
    "founder",
    "funnel",
    "gaming",
    "gant chart",
    "git",
    "github",
    "go to market",
    "go-to-market",
    "go-to-market strategy",
    "goal oriented",
    "google ads",
    "google analytics",
    "google data studio",
    "google tag manager",
    "graphic design",
    "graphql",
    "group working session",
    "growth",
    "growth and lifecycle marketing",
    "growth hacker",
    "growth marketing strategy",
    "gtm",
    "gtm strategy",
    "hadoop",
    "heap analytics",
    "heap dump analysis",
    "high availability",
    "hive",
    "hootsuite",
    "html",
    "html5",
    "html5 app",
    "hubspot",
    "ide",
    "implementing digital marketing strategies",
    "industry trends",
    "informatica intelligent cloud services",
    "instagram",
    "instapage",
    "integrations",
    "interactive tools",
    "interviews",
    "inventory control",
    "inventory selections",
    "investment banking",
    "invision",
    "ios",
    "it operations",
    "java",
    "java enterprise edition",
    "javascript",
    "jira",
    "jquery",
    "kensho",
    "key buyer personas",
    "key customer benefits",
    "keyword research",
    "keyword targeting",
    "keyword/audience research",
    "kissmetrics",
    "kpi",
    "laddering technqiues",
    "landing page optimization",
    "lead nurturing",
    "lean",
    "lean startup",
    "legal",
    "lifecycle marketing",
    "linkedin",
    "linkedin ads",
    "lob",
    "logo design",
    "lookr",
    "ltv",
    "machine learning",
    "mailchimp",
    "manage monthly budget",
    "mapreduce",
    "market",
    "market analysis",
    "market research",
    "market research & analysis",
    "market segmentation",
    "market trends",
    "marketing automation",
    "marketing automation workflows",
    "marketing campaigns",
    "marketing funnel management",
    "marketing management",
    "marketing mix models",
    "marketing planning",
    "marketo",
    "martech",
    "merchandising",
    "metadata management",
    "microsoft office",
    "minimal viable product",
    "mixpanel",
    "mobile app",
    "mobile marketing",
    "mobile web",
    "mockups",
    "modelling",
    "motivation theory",
    "mql",
    "ms word",
    "multivariate regression",
    "mvp",
    "mysql",
    "new product marketing",
    "node",
    "operating systems",
    "ops",
    "optimizely",
    "oracle",
    "organizational ability",
    "organizational skills",
    "out-of-the-box brand building",
    "paid search",
    "paid social",
    "paid social media advertising",
    "pardot",
    "performance",
    "php",
    "pig",
    "piktochart",
    "pinterest",
    "pitching",
    "platform services",
    "playbook",
    "powerpoint",
    "ppc",
    "prds",
    "pricing",
    "pricing frameworks",
    "pricing strategies",
    "problem",
    "product",
    "product design",
    "product ecosystem",
    "product implementation",
    "product launch",
    "product lifecycle",
    "product management",
    "product manager",
    "product marketing",
    "product requirement document",
    "product specs",
    "product vision",
    "professional affairs",
    "project management",
    "public relations",
    "python",
    "qa",
    "quality assurance",
    "quantitative",
    "quantitative model",
    "query language",
    "r&d",
    "rails",
    "react",
    "reactnative",
    "realm mobile database",
    "reduced cpa/cpl",
    "regulatory",
    "release",
    "relevant demographic specialization",
    "reliability",
    "requirements analysis",
    "requirements gathering",
    "research",
    "research and development",
    "resolve dependencies",
    "results-oriented",
    "retail tech",
    "revenue growth",
    "revenue impact",
    "roa",
    "roadmap",
    "roadmunk",
    "roi",
    "ruby",
    "rust",
    "saas",
    "saas attribution modeling",
    "sales",
    "sales and marketing",
    "sales enablement assets",
    "salesforce",
    "sas macros",
    "sas stat",
    "sass",
    "scala",
    "scalability",
    "scope",
    "scripting",
    "scrum",
    "sdlc",
    "search and social",
    "search engine marketing",
    "search engine optimization",
    "search processing",
    "seasonal campaigns",
    "segmentation",
    "segments",
    "self-motivate",
    "self-serve channels",
    "self-starter",
    "sell your ideas",
    "sem",
    "seo",
    "ship",
    "sketch",
    "slack",
    "slideshare",
    "sme capacity",
    "social media",
    "social media marketing",
    "social media metrics",
    "social media platforms",
    "social studio",
    "software",
    "software development",
    "software development lifecycle",
    "software engineering",
    "sold channels",
    "soluton briefs",
    "spark",
    "specification",
    "sprint",
    "spss",
    "sql",
    "sre",
    "stakeholders",
    "startup",
    "status",
    "strategy",
    "stream data",
    "success metrics",
    "swift",
    "swot analysis",
    "tableau",
    "target segments",
    "technical",
    "technical architecture",
    "technical documentation",
    "telemarketing",
    "tentpole",
    "teradata",
    "testing",
    "thread dump analysis",
    "tradeshows",
    "trello",
    "triage issues",
    "tsql",
    "twilio",
    "twitter",
    "twitter ads",
    "typescript",
    "ui",
    "unbounce",
    "usability",
    "use cases",
    "user centric",
    "user empathy",
    "user experience",
    "user persona",
    "user requirements",
    "user research",
    "user stories",
    "user test",
    "user-centered",
    "user-centered design",
    "ux design",
    "ux/ui",
    "validate",
    "vendor management",
    "venture capital",
    "verbal communication skills",
    "video editing",
    "video marketing",
    "video production",
    "vision",
    "vue.js",
    "web design",
    "webpack",
    "whitepapers",
    "wireframing",
    "wordpress",
    "work collaboratively",
    "written",
    "youtube",
]
    
            export { pm_marketing_keywords }
            