
var synonyms = [
    ["machine learning","ml"],
    ["ai","artificial intelligence"],
    ["engineer","engineering"],
    ["user centric","user-centric"],
    ["wireframing","wireframes","wireframe","wire frame"],
    ["specification","spec","specs","product spec"],
    ["detail-oriented","detail oriented"],
    ["a/b testing","ab test","ab testing","a/b test"],
    ["micro-services","microservices"],
    ["aws","amazon web services"],
    ["backend","back-end","back end"],
    ["frontend","front-end","front end"],
    ["rest applications","restful api"],
    ["spring mvc","spring boot","spring data","spring framework"],
    ["gcp","google cloud platform"],
    ["object-oriented","object oriented"],
    ["test-driven development","tdd","test-driven-development","test driven development"],
    ["apache solr","solr"],
    ["apache kafka","kafka"],
    ["debugger","debugging"],
    ["analytics","analysis"],
    ["cross-functional","cross-functionally"],
    ["google cloud storage","gcs"],
    ["real-time","real time","realtime"],
    ["reactjs","react.js","react","react js"],
    ["vue","vuejs","vue.js"],
    ["node.js","nodejs","node"],
    ["continuous integration","ci"],
    ["postgres","postgresql","postgressql"],
    ["cms","content management system"],
    ["crm","customer relationship management"],
    ["cascading style sheets","css","css3"],
    ["ux/ui","ui/ux"],
    ["html","html5"],
    ["javascript","js"],
    ["angular","angularjs","angular.js"],
]

export { synonyms }
