
    var marketing_keywords = [
        "a/b test",
    "account optimization",
    "accounting",
    "ad-hoc",
    "adobe creative cloud",
    "adobe creative suite",
    "adobe illustrator",
    "adobe photoshop",
    "adobe suite",
    "adtech",
    "advertising campaign management",
    "advertising campaigns",
    "advertising strategy",
    "agile",
    "art direction",
    "automation tools",
    "autopilot",
    "azuredb",
    "b2b",
    "b2b technology",
    "b2c",
    "b2g",
    "babel",
    "base sas",
    "bing",
    "bing ads",
    "bootstrap",
    "brand management",
    "brightedge",
    "browserify",
    "btravis ci",
    "buffer",
    "business reports",
    "business strategy",
    "campaign creation",
    "campaign management",
    "campaign plans",
    "canva",
    "client acquisition",
    "clustering",
    "cms",
    "commercial operations",
    "communications",
    "conflict resolution",
    "conjoint",
    "consumer decision frameworks",
    "consumer psychology",
    "content development",
    "content marketing",
    "copywriting",
    "create report",
    "creative production",
    "critical analysis",
    "critical thinking",
    "crm",
    "cross-sell path",
    "css",
    "customer engagement",
    "customer oriented",
    "customer-facing marketing tools",
    "data analysis",
    "data science",
    "data studio",
    "data visualization",
    "decision trees",
    "decision-making",
    "demand generation",
    "digital campaigns",
    "digital marketing",
    "digital-minded",
    "direct mail marketing",
    "distribution channels",
    "docusign",
    "domo",
    "doubleclick",
    "eloqua",
    "email campaigns",
    "email marketing",
    "etl",
    "event budget tracker",
    "event marketing",
    "evergreen campaigns",
    "excel",
    "excel / spreadsheet",
    "experimental test",
    "facebook",
    "facebook ads",
    "facebook ads manager",
    "finance",
    "firebase",
    "flexbox",
    "git",
    "github",
    "go-to-market",
    "google ads",
    "google analytics",
    "google data studio",
    "google tag manager",
    "graphic design",
    "group working session",
    "growth and lifecycle marketing",
    "growth hacker",
    "growth marketing strategy",
    "gtm",
    "hadoop",
    "heap dump analysis",
    "hive",
    "hootsuite",
    "html5",
    "hubspot",
    "implementing digital marketing strategies",
    "informatica intelligent cloud services",
    "instagram",
    "instapage",
    "interactive tools",
    "inventory selections",
    "kensho",
    "key buyer personas",
    "key customer benefits",
    "keyword research",
    "keyword targeting",
    "keyword/audience research",
    "kpi",
    "laddering technqiues",
    "landing page optimization",
    "lead nurturing",
    "lifecycle marketing",
    "linkedin",
    "linkedin ads",
    "lob",
    "logo design",
    "lookr",
    "ltv",
    "mailchimp",
    "manage monthly budget",
    "mapreduce",
    "market research",
    "market research & analysis",
    "market segmentation",
    "marketing automation",
    "marketing automation workflows",
    "marketing campaigns",
    "marketing funnel management",
    "marketing management",
    "marketing mix models",
    "marketing planning",
    "marketo",
    "martech",
    "microsoft office",
    "mobile marketing",
    "modelling",
    "motivation theory",
    "ms word",
    "multivariate regression",
    "mysql",
    "new product marketing",
    "oracle",
    "out-of-the-box brand building",
    "paid search",
    "paid social",
    "paid social media advertising",
    "pardot",
    "pig",
    "piktochart",
    "pinterest",
    "pitching",
    "playbook",
    "powerpoint",
    "ppc",
    "pricing strategies",
    "product launch",
    "professional affairs",
    "project management",
    "public relations",
    "reduced cpa/cpl",
    "relevant demographic specialization",
    "results-oriented",
    "retail tech",
    "revenue impact",
    "roa",
    "roi",
    "saas attribution modeling",
    "sales enablement assets",
    "salesforce",
    "sas macros",
    "sas stat",
    "sass",
    "scripting",
    "scrum",
    "search and social",
    "search engine marketing",
    "search engine optimization",
    "seasonal campaigns",
    "segmentation",
    "self-serve channels",
    "sem",
    "seo",
    "slideshare",
    "sme capacity",
    "social media",
    "social media marketing",
    "social media metrics",
    "social media platforms",
    "social studio",
    "sold channels",
    "soluton briefs",
    "spark",
    "spss",
    "tableau",
    "target segments",
    "telemarketing",
    "tentpole",
    "teradata",
    "thread dump analysis",
    "tsql",
    "twilio",
    "twitter",
    "twitter ads",
    "unbounce",
    "ux design",
    "vendor management",
    "video editing",
    "video marketing",
    "video production",
    "web design",
    "webpack",
    "whitepapers",
    "wordpress",
    "youtube",

    ]

    export { marketing_keywords }
    