var swe_keywords =

    [    "5g",
    "a/b test",
    "aaa",
    "ab testing",
    "abap",
    "abcl",
    "accessibility",
    "acl",
    "actionscript",
    "activemq",
    "ad features",
    "ad technology",
    "ada",
    "adaptive autosar",
    "adas sw system",
    "adas/ad feature",
    "ado.net",
    "adobe aem",
    "adobe powerbi",
    "adtech",
    "advanced analytics",
    "advanced analytics platforms",
    "advanced analytics solutions",
    "advertising performance metrics",
    "afnix",
    "agile",
    "agile methodologies",
    "agile methods",
    "agile planning",
    "agile scrum team",
    "agile software development",
    "agile tools and processes",
    "agile work processes and tools",
    "agilescrum sprint events and cycles",
    "agora",
    "ai",
    "airflow",
    "ajax",
    "alf",
    "algol",
    "algorithm design",
    "algorithm development",
    "algorithms",
    "alice",
    "amazon web services",
    "analysis",
    "analytic capabilities",
    "analytical",
    "analytical and problem",
    "analytical capabilities",
    "analytical problem-solving",
    "analytical support",
    "analytical tools and techniques",
    "analytics",
    "analytics products",
    "anaplan",
    "android",
    "angular",
    "angularjs",
    "ansible",
    "apache",
    "apache airflow",
    "apache camel",
    "apache druid",
    "apache flink",
    "apache kafka",
    "apache solr",
    "apache spark",
    "apex",
    "api",
    "apl",
    "app design",
    "applescript",
    "application code",
    "application developer",
    "application development",
    "application layer protocol",
    "application scaling",
    "apty",
    "architectural direction",
    "architectural video presentations",
    "architecture",
    "artificial intelligence",
    "asana",
    "ascii encoding",
    "asio",
    "asp",
    "asp.net",
    "aspice",
    "assembly",
    "asynchronous systems",
    "atlassian",
    "autoit",
    "automate processes",
    "automate reporting",
    "automated ci/cd",
    "automated tests",
    "automating asset inspections processes",
    "automation of processes",
    "automation solutions",
    "automotive adas",
    "automotive adas customer features",
    "automotive camera based adas",
    "automotive code",
    "automotive component",
    "automotive logistics",
    "automotive supplier interaction",
    "awk",
    "aws",
    "aws kinesis",
    "aws redshift",
    "azure",
    "b2b product solutions",
    "b2b technology",
    "babel",
    "back end",
    "back-end",
    "back-end data display",
    "back-end framework",
    "back-end programming language",
    "backbone",
    "backbone.js",
    "backend",
    "backlog",
    "balsamiq",
    "base sas",
    "basecamp",
    "bash",
    "basic",
    "batch data ingestion",
    "batch process",
    "bbc basic",
    "beanshell",
    "beta",
    "big customer problems",
    "big data",
    "big data technologies",
    "bigquery",
    "bitbucket",
    "blazor",
    "bliss",
    "blockchain",
    "books",
    "bootstrap",
    "branding/website design",
    "breakdown complex problems",
    "browserify",
    "buffer",
    "build solutions",
    "building codes and standards",
    "business intelligence technologies",
    "c",
    "c#",
    "c++",
    "c/c++",
    "cakephp",
    "cascading style sheets",
    "cassandra",
    "cecil",
    "cgi",
    "change management",
    "change management programs",
    "charity",
    "chart.js",
    "chuck",
    "chyrp",
    "ci/cd",
    "cifs and citrix",
    "cilk",
    "circleci",
    "classification",
    "clean",
    "cleaning procedures",
    "cleo",
    "cli",
    "client facing",
    "client satisfaction",
    "clist",
    "clojure",
    "cloud",
    "cloud app adoption",
    "cloud computing",
    "cloud infrastructure",
    "cloudsearch",
    "cloudwatch",
    "clustering",
    "cms",
    "cobol",
    "cobra",
    "cocoa",
    "code review",
    "codeigniter",
    "coding",
    "coldfusion",
    "collaborate",
    "collaborate with back-end developers",
    "collaborate with web designers",
    "collaboration",
    "collaborative",
    "command line",
    "communicate",
    "communication",
    "communication skills",
    "competitive analysis",
    "compiler",
    "complex issues",
    "complex projects",
    "compliance",
    "component libraries",
    "component pascal",
    "computational analytics",
    "computer architecture",
    "computer engineering",
    "computer science",
    "computer security",
    "computer vision",
    "computer vision models",
    "concept diagrams",
    "concur",
    "concurrent pascal",
    "confluence",
    "connectivity technologies",
    "containerization",
    "content management",
    "content management system",
    "contingency plan",
    "continuous improvement",
    "continuous improvement activities",
    "continuous integration",
    "continuous integration and deployment",
    "continuous learning",
    "conversion",
    "cookies",
    "corba",
    "correction protocol",
    "coupa",
    "cpq",
    "create processes",
    "create report",
    "create web pages",
    "crm",
    "crm pipeline",
    "cronjobs",
    "cross functional",
    "cross functional collaboration",
    "cross-browser compatibility",
    "cross-functional",
    "cross-functional collaboration",
    "cross-functionally",
    "cryptocurrency",
    "css",
    "csv",
    "cte",
    "cuda",
    "curl",
    "current web trends",
    "curry",
    "customer analytics",
    "customer engagement",
    "customer features",
    "customer needs",
    "customer service",
    "customer stories",
    "customer success",
    "customer success metrics",
    "customer value",
    "dap",
    "dashboard specifications",
    "dasl",
    "data",
    "data analysis",
    "data analytics",
    "data and analysis",
    "data consolidation",
    "data driven",
    "data driven decisions",
    "data driven solutions",
    "data ingestion",
    "data lake",
    "data mining",
    "data modeling",
    "data models",
    "data pipeline",
    "data platform",
    "data presentation",
    "data processing",
    "data reporting",
    "data science",
    "data sets",
    "data sheets",
    "data solutions",
    "data storytelling",
    "data strategy",
    "data structures",
    "data studio",
    "data validation exercises",
    "data visualization",
    "data visualization tools",
    "data warehouse",
    "data-driven",
    "data-driven analysis",
    "data-driven approach",
    "data-driven metrics",
    "data-informed techniques",
    "data-powered products",
    "database",
    "database administration",
    "database architecture",
    "databricks",
    "dataflow",
    "dataflow/beam",
    "dataproc",
    "dataset",
    "dds",
    "debugger",
    "debugging",
    "decision making",
    "decision trees",
    "deductive reasoning",
    "deep learning",
    "delphi",
    "deployment",
    "descriptive / predictive models",
    "design",
    "design guides and prototypes",
    "design patterns",
    "design review",
    "design tools and workflows",
    "desktop and mobile app frameworks",
    "detail oriented",
    "detail-oriented",
    "development",
    "development life cycle",
    "device drivers",
    "devops",
    "devops practices",
    "dhcp",
    "dibol",
    "digital adoption platform",
    "digital products",
    "digital strategy",
    "digital transformation program",
    "discovery",
    "discovery assumption mapping",
    "distributed and parallel systems",
    "distributed applications",
    "distributed products",
    "distributed storage",
    "distributed system",
    "django",
    "dns",
    "docker",
    "docker-compose",
    "documentation",
    "docusign",
    "dom",
    "domo",
    "doubleclick",
    "dpdk",
    "draft contacts",
    "dreamweaver",
    "drive revenue",
    "drupal",
    "dynamic web page design",
    "dynamically-generated segments",
    "dynamodb",
    "e-commerce",
    "early employee",
    "early stage startups",
    "easy-to-understand concepts",
    "easymock",
    "ebpf/xdp",
    "ec2",
    "econometric modeling",
    "ecs",
    "eecs",
    "eiffel",
    "elasticache",
    "elasticsearch",
    "elt",
    "embedded language",
    "embedded networking",
    "embedded software testing",
    "embedded systems",
    "emerging/ground-breaking technologies",
    "enablement framework",
    "end to end process",
    "end-to-end",
    "engineer",
    "enterprise",
    "enterprise software",
    "enterprise software startup",
    "enterprise solutions",
    "entrepreneurial",
    "erlang",
    "erlang and elixir",
    "error detection",
    "es6",
    "ethernet",
    "ethics",
    "etl",
    "etl data",
    "etl data integration",
    "event budget tracker",
    "excel",
    "excel / spreadsheet",
    "experiment",
    "experimental design",
    "extreme programming",
    "f#",
    "f-script",
    "fast paced environment",
    "feature backlog",
    "feature delivery and tradeoffs",
    "feedback",
    "ffmpeg",
    "financialforce",
    "fintech",
    "firebase",
    "firewall",
    "firmware",
    "flexbox",
    "flink",
    "flux",
    "forth",
    "fortran",
    "founder",
    "framework templates",
    "fraud detection",
    "fraud detection model",
    "fril",
    "frink",
    "front end",
    "front end design",
    "front end technologies",
    "front-end",
    "front-end development",
    "front-end systems",
    "front-end web technologies",
    "frontend",
    "full stack",
    "full-stack",
    "functional programing",
    "functional programming",
    "functional qa",
    "funnel",
    "fusion",
    "gaming",
    "gant chart",
    "gate",
    "gcp",
    "gcs",
    "generating pipeline",
    "git",
    "github",
    "gitlab",
    "global design system",
    "gnustep",
    "go",
    "golang",
    "google bigquery",
    "google cloud",
    "google cloud platform",
    "google cloud storage",
    "google suite",
    "google tag manager",
    "google workspace",
    "googleadobe analytics",
    "gpu",
    "grape",
    "graphql",
    "gre",
    "grid edge technologies",
    "groovy",
    "grunt",
    "gsuite",
    "guava",
    "guice",
    "gulp",
    "hadoop",
    "hardware",
    "haskell",
    "hbase",
    "hci",
    "heap analytics",
    "hellosign integration ecosystem",
    "heroku",
    "hive",
    "hosting environment",
    "html",
    "html5 app",
    "http",
    "http headers",
    "http methods",
    "http payloads",
    "http response codes",
    "human centered design",
    "hypertalk",
    "hypothesis driven outcomes",
    "iaas",
    "ici",
    "iconography",
    "identity typography",
    "idl",
    "ike",
    "imagemagick",
    "implementing digital marketing strategies",
    "inductive reasoning",
    "information systems",
    "informing standards",
    "infrastructure",
    "infrastructure-as-code",
    "integration",
    "inter-related technologies",
    "interaction patterns",
    "interaction standards",
    "interactive tools",
    "intercal",
    "interior design or architecture",
    "invision",
    "io",
    "iot",
    "ip",
    "ip creation/tracking",
    "ip forwarding",
    "ip management",
    "ipv6",
    "iso 26262",
    "it operations",
    "iterative development",
    "iterative development process",
    "iterative user research",
    "j2ee",
    "janus",
    "jass",
    "java",
    "java enterprise edition",
    "javascript",
    "jboss",
    "jenkins",
    "jest",
    "jira",
    "joomla",
    "joule",
    "jovial",
    "joy",
    "jquery",
    "json",
    "junit",
    "jupyter notebook",
    "kafka",
    "kanban",
    "kensho",
    "kernel",
    "key accounts",
    "key buyer personas",
    "key customer programs",
    "key performance indicators",
    "key performance metrics",
    "keyword research",
    "keyword/audience research",
    "kinesis",
    "kissmetrics",
    "kite",
    "komodo",
    "komodo’s data and algorithms",
    "kotlin",
    "kpi metrics",
    "kubernetes",
    "labview",
    "laddering technqiues",
    "lambda",
    "lamp",
    "laravel",
    "latency",
    "lava",
    "leadership",
    "lean",
    "lean experiments",
    "lean startup",
    "leda",
    "less",
    "lightning",
    "limbo",
    "linked lists",
    "linux",
    "linux programming",
    "linux/unix",
    "lisaac",
    "lisp",
    "load changes",
    "lob",
    "logistics management",
    "logo",
    "lookup",
    "lua",
    "lucene",
    "machine learning",
    "machine learning algorithm",
    "machine learning languages and packages",
    "machine learning model",
    "macos",
    "maker language",
    "manage accounts",
    "mandriva linux",
    "mantisbt",
    "map reduce",
    "mapreduce",
    "matlab",
    "maven",
    "mdn",
    "memcache",
    "mercurial",
    "metaquotes language",
    "metrics",
    "micro-services",
    "microservices",
    "microsoft asp.net",
    "microsoft technologies",
    "middleware systems",
    "migration",
    "minimal viable product",
    "miro",
    "misra",
    "mixpanel",
    "ml",
    "ml model",
    "mobile app",
    "mobile development",
    "mobile game development",
    "mobile marketing",
    "mobile technologies",
    "mobile web",
    "mock-ups",
    "mockito",
    "modelling",
    "modula-2",
    "modula-3",
    "mondrian",
    "mongo",
    "mongodb",
    "monitoring",
    "montoring regulations",
    "moo",
    "motivation theory",
    "moto",
    "mpi",
    "ms access",
    "ms power bi",
    "ms-dos",
    "ms-windows",
    "msxml",
    "multi-stage projects",
    "multi-tenant",
    "multi-threaded",
    "multimodal interactions",
    "multivariate regression",
    "mural",
    "mvc",
    "mvp",
    "mvvm",
    "mysql",
    "nat",
    "natural language processing",
    "ncurses",
    "negotiate agreements",
    "nemerle",
    "netcdf",
    "netsuite",
    "netty",
    "network and information security",
    "network programming",
    "networking",
    "neural network",
    "nginx",
    "nlp",
    "node",
    "node.js",
    "nodejs",
    "non-relational databases",
    "nosql",
    "numpy",
    "nxt-g",
    "oauth",
    "oberon",
    "object oriented",
    "object-oriented",
    "object-oriented design",
    "object-oriented programming",
    "object-z",
    "objective-c",
    "obliq",
    "ocaml",
    "occam",
    "okrs",
    "okrs pirate metrics",
    "olap",
    "oop",
    "opal",
    "opencl",
    "openid",
    "openssl",
    "operating systems",
    "operational improvements",
    "operational metrics",
    "ops5",
    "opsgenie",
    "optics",
    "optimization",
    "optimizely",
    "optimizers",
    "oracle",
    "oral and written communication",
    "organizational ability",
    "orm",
    "os development",
    "oxygene",
    "oz",
    "p4 language",
    "paas",
    "pandas",
    "parallelization",
    "parsers",
    "pascal",
    "pcastl",
    "people analytics",
    "people management",
    "performance dashboards",
    "performance improvement",
    "performance metrics",
    "performance testing",
    "performance validation",
    "perl",
    "php",
    "phprojekt",
    "phpunit",
    "pict",
    "pig",
    "piktochart",
    "pipeline",
    "pipeline analysis",
    "pivot table",
    "pl/c",
    "pl/i",
    "pl/sql",
    "platform tools",
    "play framework",
    "pliant",
    "plotly dash",
    "pmbok",
    "pmp",
    "point cloud processing",
    "policy development",
    "poplog",
    "positive reviews",
    "post-launch optimizations",
    "postcss",
    "postgres",
    "postgresql",
    "postscript",
    "powershell",
    "ppc",
    "practical a/b testing",
    "predictive intelligence",
    "predictive model",
    "press page",
    "presto",
    "privacy protections",
    "probabilistic filters",
    "probability",
    "problem solving skills",
    "process analysis",
    "process improvement",
    "process management",
    "process optimization",
    "product analytics",
    "product and release planning sessions",
    "product delivery",
    "product demonstration",
    "product demos",
    "product design",
    "product development process",
    "product enhancement",
    "product expert",
    "product features",
    "product improvements",
    "product launch plan",
    "product life-cycle",
    "product lifecycle",
    "product management",
    "product manager",
    "product marketing",
    "product or program management",
    "product pipeline",
    "product pipeline management",
    "product usage models",
    "product ux",
    "product vision",
    "product vision and strategy",
    "product-oriented quantitative analysis",
    "production agencyvendor management",
    "production defects",
    "program management",
    "program planning",
    "programming",
    "programming language",
    "programming systems engineering",
    "prograph",
    "project manageer",
    "project management",
    "project management tools",
    "project plans",
    "project risks",
    "project/release management",
    "prolog",
    "prototype",
    "prototype system",
    "prototyping",
    "proxy",
    "pubsub",
    "pure data",
    "pyspark",
    "python",
    "pytorch",
    "q",
    "qa metrics",
    "qos",
    "quality assurance",
    "quality production",
    "quality system",
    "quantitative",
    "quantitative analysis",
    "quantitative model",
    "query",
    "r",
    "rabbit mq",
    "rabbitmq",
    "radio access networks",
    "rails",
    "rapid prototyping",
    "rapidweaver",
    "rapira",
    "raspberry pi",
    "ravendb",
    "react",
    "react native",
    "react.js",
    "reactjs",
    "reactnative",
    "real-time analysis",
    "rebol",
    "recommendations",
    "redis",
    "redshift",
    "reduced cpa/cpl",
    "redux",
    "regex",
    "regression",
    "relational database",
    "relationship management",
    "release",
    "release criteria and management",
    "release infrastructure",
    "release management",
    "reliability",
    "report automation",
    "report templates",
    "research",
    "responsive",
    "responsive design",
    "rest",
    "rest apis",
    "rest applications",
    "restful api",
    "restlet",
    "retail sales process",
    "revenue analysis",
    "revenue impact",
    "revenue quota",
    "revolution",
    "rexx",
    "risk management",
    "roadmap",
    "roadmap planning",
    "roadmap strategy",
    "roadmunk",
    "robots",
    "roi",
    "role-based access",
    "roop",
    "root cause analysis",
    "ros",
    "routing",
    "routing protocol",
    "rpg",
    "ruby",
    "ruby on rails",
    "rust",
    "s-lang",
    "s-plus",
    "s3",
    "saas",
    "saas attribution modeling",
    "saas models outcome-based models",
    "saas product",
    "saas sale",
    "salesforce",
    "salesforce app exchange",
    "salesforce crm",
    "salsa",
    "saml integrations",
    "sap",
    "sas",
    "sas macros",
    "sas stat",
    "scala",
    "scalable",
    "scalable processes",
    "schema",
    "scientific computing",
    "scikit learn",
    "scikit-learn",
    "scikitlearn",
    "scipy",
    "scope",
    "scripting",
    "scrum",
    "scrum ceremonies",
    "scrum methodologies",
    "scrum processes",
    "sdlc",
    "search engine optimization",
    "security",
    "security compliance",
    "sed",
    "selenium",
    "self",
    "self-motivate",
    "self-starter",
    "sell your ideas",
    "sensor calibration",
    "seo",
    "server-side scripting",
    "service delivery",
    "service desk",
    "service level agreements",
    "service management products",
    "service production marketing technology",
    "service roadmap",
    "sftp",
    "sgml",
    "shell",
    "shell scripting",
    "signal processing",
    "simula",
    "simulink",
    "sip",
    "site reliability",
    "sketch",
    "sklearn",
    "sla",
    "slack",
    "slate",
    "slideshare",
    "small",
    "smalltalk",
    "smil",
    "snmp",
    "snobol",
    "soap",
    "social & mobile applications",
    "social distancing guidelines",
    "social media apps",
    "social media software",
    "software",
    "software + hardware",
    "software architecture",
    "software developer",
    "software development",
    "software development life cycle",
    "software development roadmap",
    "software engineer",
    "software sales",
    "software stacks",
    "software workflow",
    "software-as-as-service",
    "software-defined networking",
    "solr",
    "solutions",
    "soluton briefs",
    "sonarqube",
    "sorting algorithms",
    "sound legal judgment",
    "source / version control",
    "source code",
    "spam",
    "spark",
    "specification development",
    "spin",
    "spl2",
    "splunk",
    "spring",
    "spring boot",
    "spring data",
    "spring framework",
    "spring mvc",
    "sprint",
    "spss",
    "sql",
    "sql server",
    "sql-like scripting language",
    "sqlalchemy",
    "sqlite",
    "sqs",
    "sr",
    "sr management",
    "ssh",
    "ssi",
    "stage gate process",
    "standard practices",
    "stata",
    "state management",
    "statistical methodologies",
    "statistical methods",
    "statistical modeling",
    "statistical packages",
    "statistics",
    "step functions",
    "storage systems and management",
    "storybook",
    "strategic growth projects",
    "strategic learning management system",
    "strategic planning",
    "strategic projects",
    "strategy",
    "streaming",
    "stress tolerance",
    "structural layouts",
    "styling and color design",
    "subversion",
    "supervised",
    "sw production release",
    "swift",
    "switching",
    "symfony",
    "syslog",
    "system integration",
    "tableau",
    "target segments",
    "task automation",
    "task management",
    "tcl",
    "tcl/tk",
    "tcp",
    "tcp/ip",
    "tdd",
    "teamwork",
    "tech stack",
    "tech support",
    "technical architecture",
    "technical documentation",
    "technical functionality",
    "technical implementation methods",
    "technical product management",
    "technical reporting",
    "technology trends and architectures",
    "telemarketing",
    "tensorflow",
    "teradata",
    "terraform",
    "test & quality",
    "test automation",
    "test development",
    "test driven development",
    "test infrastructure",
    "test plan",
    "test planning",
    "test strategies",
    "test-driven development",
    "test-driven-development",
    "testing",
    "tex and latex",
    "timeline planning",
    "tms",
    "tomcat",
    "tooling development",
    "top-tier management",
    "transactions",
    "travis ci",
    "travisci",
    "trello",
    "trend analysis",
    "troubleshooting",
    "troubleshooting/debugging",
    "tsql",
    "tuning",
    "tunneling",
    "turing",
    "twilio",
    "twitter ads",
    "tws",
    "typescript",
    "typical design tools",
    "uat",
    "ubuntu",
    "udp",
    "ui",
    "ui design and development",
    "ui engineering",
    "ui standards",
    "ui toolkits and frameworks",
    "ui/ux",
    "umbraco",
    "unbounce",
    "unified modeling language",
    "unit test",
    "unix",
    "unix programming",
    "unix shell",
    "unsupervised",
    "upsell & cross sell",
    "uptime",
    "url",
    "usability",
    "usability studies",
    "user centric",
    "user design",
    "user empathy",
    "user experience",
    "user features",
    "user feedback",
    "user interaction",
    "user interaction design",
    "user interface",
    "user interface design",
    "user persona",
    "user requirements",
    "user research",
    "user scenarios",
    "user stories",
    "user story writing",
    "user test",
    "user testing plans",
    "user testing sessions",
    "user-centered",
    "user-centered design",
    "user-centered design techniques",
    "ux",
    "ux design",
    "ux design methodologies",
    "ux design principles",
    "ux design processes",
    "ux patterns",
    "ux research methods",
    "ux vision & strategy",
    "ux/design language style libraries",
    "ux/ui",
    "validate",
    "validation",
    "vbscript",
    "vendoragency management",
    "verilog",
    "version control",
    "version control system",
    "version repository",
    "vertica",
    "vhdl",
    "vi",
    "visual basic",
    "visual brand",
    "visual design",
    "visual foxpro",
    "visual studio",
    "visualization software",
    "vlan",
    "vrml",
    "vrrp",
    "vue",
    "vue.js",
    "walkme",
    "wap/wml",
    "wcag 2.1 compliance standards",
    "wcf",
    "weave flux",
    "web",
    "web accessibility standards.understanding",
    "web api",
    "web application",
    "web application development",
    "web based software applications",
    "web design",
    "web developer",
    "web development",
    "web production",
    "web projects",
    "web rollout",
    "web services",
    "web site",
    "web site registration",
    "web standards",
    "web technologies",
    "web technologies.experience",
    "webdriverio",
    "webkit",
    "webpack",
    "website content display",
    "website management tools",
    "website navigation optimization",
    "website performance optimization",
    "whatfix",
    "whitepapers",
    "windows powershell",
    "wireframe",
    "wireframing",
    "wms",
    "wordpress",
    "work collaboratively",
    "wpf",
    "writing modules",
    "wsdl",
    "wsgi",
    "xaml",
    "xaraya",
    "xhtml",
    "xl",
    "xml",
    "xotcl",
    "xsl",
    "yui",
    "zendesk",
    "zikula",
]

            export { swe_keywords }
