var swe_nice_to_haves =
            
    [    "5g",
    "a/b test",
    "ab testing",
    "ad features",
    "ad technology",
    "adobe aem",
    "adobe analytics",
    "adobe powerbi",
    "adtech",
    "advanced analytics",
    "advanced analytics platforms",
    "advanced analytics solutions",
    "advertising performance metrics",
    "afnix",
    "agile",
    "agora",
    "airflow",
    "algolia",
    "algorithm design",
    "algorithm development",
    "algorithms",
    "amplitude",
    "analytic capabilities",
    "ansible",
    "anycast",
    "app security",
    "application scaling",
    "asana",
    "ascii encoding",
    "asynchronous systems",
    "atlassian",
    "automate processes",
    "automate reporting",
    "automated ci/cd",
    "automated testing",
    "automated tests",
    "automating asset inspections processes",
    "automation of processes",
    "automation solutions",
    "automotive adas",
    "automotive adas customer features",
    "automotive camera based adas",
    "automotive code",
    "automotive component",
    "automotive logistics",
    "automotive supplier interaction",
    "b2b product solutions",
    "b2b technology",
    "batch data ingestion",
    "beam",
    "bgp",
    "bitbucket",
    "blazor",
    "bliss",
    "bootstrap",
    "browserify",
    "chromium",
    "classification",
    "clustering",
    "code review",
    "competitive analysis",
    "compliance",
    "concept diagrams",
    "confluence",
    "connectivity technologies",
    "containerization",
    "continuous improvement",
    "continuous improvement activities",
    "continuous integration",
    "continuous integration and deployment",
    "continuous learning",
    "correction protocol",
    "crm",
    "crm pipeline",
    "cross-browser compatibility",
    "csv",
    "dash",
    "datadog",
    "dataflow",
    "debugging",
    "decision trees",
    "descriptive and predictive models",
    "descriptive models",
    "descriptive/predictive models",
    "devops",
    "dhcp",
    "discovery assumption mapping",
    "distributed and parallel systems",
    "distributed applications",
    "distributed products",
    "distributed storage",
    "dns",
    "docker",
    "docker-compose",
    "dom",
    "domo",
    "dreamweaver",
    "e-commerce",
    "easymock",
    "econometric modeling",
    "embedded language",
    "embedded networking",
    "embedded software testing",
    "embedded systems",
    "entrepreneurial",
    "ethernet",
    "etl",
    "etl data",
    "etl data integration",
    "excel",
    "ffmpeg",
    "figma",
    "financialforce",
    "fintech",
    "firefox",
    "fmp4",
    "framework templates",
    "fraud detection",
    "fraud detection model",
    "functional qa",
    "funnel",
    "fusion",
    "generating pipeline",
    "github",
    "gitlab",
    "gnustep",
    "google analytics",
    "google suite",
    "gtm",
    "helm",
    "heroku",
    "hls",
    "hubspot",
    "iaas",
    "iconography",
    "illustrator",
    "infoblox",
    "invision",
    "jira",
    "jsunit",
    "junit",
    "jupyter notebook",
    "kanban",
    "keras",
    "kernel",
    "kube flow",
    "kubeflow",
    "laddering techniques",
    "ltm",
    "lucene",
    "matlab",
    "mdn",
    "micro-services",
    "microservices",
    "miro",
    "mixpanel",
    "mocha",
    "mockito",
    "motivation theory",
    "mpi",
    "ms access",
    "ms power bi",
    "multivariate regression",
    "network/socket",
    "neural network",
    "olap",
    "opencv",
    "openshift",
    "opsgenie",
    "organizational ability",
    "parallelization",
    "pendo",
    "performance improvement",
    "performance metrics",
    "photoshop",
    "phprojekt",
    "pig",
    "piktochart",
    "pipeline",
    "pmbok",
    "point cloud processing",
    "prediction algorithms",
    "predictive models",
    "privacy protections",
    "probabilistic filters",
    "process improvement",
    "product analytics",
    "product design",
    "project management",
    "pubsub",
    "pulumi",
    "puppet",
    "qos",
    "quantitative analysis",
    "quantitative model",
    "qunit",
    "radio access networks",
    "rapid prototyping",
    "rapidweaver",
    "report automation",
    "report templates",
    "roadmap planning",
    "roadmap strategy",
    "roadmunk",
    "ros",
    "s-lang",
    "salesforce crm",
    "sap",
    "scrum",
    "selenium",
    "sgml",
    "signal processing",
    "sip",
    "sketch",
    "slideshare",
    "software architecture",
    "software security",
    "solr",
    "sorting algorithms",
    "spark",
    "splunk",
    "statistical methods",
    "statistical modeling",
    "statistical packages",
    "statistics",
    "strategic planning",
    "supervised learning",
    "system integration",
    "systemc",
    "technical documentation",
    "tensorflow",
    "terraform",
    "test automation",
    "test development",
    "test driven development",
    "test infrastructure",
    "test-driven development",
    "test-driven-development",
    "testing",
    "tex and latex",
    "trello",
    "twilio",
    "tws",
    "typography",
    "uat",
    "unit test",
    "unix shell",
    "unsupervised learning",
    "user test",
    "verilog",
    "vhdl",
    "vi",
    "vim/vi",
    "visual studio",
    "visualization software",
    "vrrp",
    "walkme",
    "wcag",
    "weave flux",
    "web security",
    "webdriverio",
    "webkit",
    "whatfix",
    "xl deploy",
    "zikula",
]
    
            export { swe_nice_to_haves }
            