var swe_essentials =
            
    [    ".net",
    ".net developer",
    "actionscript",
    "ado.net",
    "ai",
    "airflow",
    "ajax",
    "alpine",
    "amazon web services",
    "android developer",
    "angular",
    "angularjs",
    "apache",
    "apache airflow",
    "apache camel",
    "apache druid",
    "apache flink",
    "apache kafka",
    "apache solr",
    "apache spark",
    "apex",
    "api",
    "apigee",
    "apollo",
    "applescript",
    "application developer",
    "application layer protocol",
    "application security engineer",
    "arduino",
    "artificial intelligence",
    "asp",
    "asp.net",
    "assembly",
    "aws",
    "aws kinesis",
    "aws redshift",
    "aws solutions architect",
    "azure",
    "babel",
    "back end",
    "back-end",
    "backbone",
    "backbone.js",
    "backend",
    "bash",
    "bbc basic",
    "bdd",
    "bgp",
    "big data",
    "bigquery",
    "blockchain",
    "blockchain developer",
    "blue yonder",
    "bsd",
    "bugzilla",
    "c",
    "c#",
    "c# developer",
    "c++",
    "cakephp",
    "cascading style sheets",
    "centos",
    "chart.js",
    "ci/cd",
    "circle",
    "clojure",
    "cloud",
    "cloud app adoption",
    "cloud computing",
    "cloud infrastructure",
    "cloudformation",
    "cms",
    "cnc programmer",
    "cobol",
    "cobra",
    "cocoa",
    "codeigniter",
    "codepipeline",
    "coldfusion",
    "collaboration",
    "collaborative",
    "command line",
    "communication",
    "communicative",
    "compiler",
    "component libraries",
    "component pascal",
    "computer architecture",
    "computer engineering",
    "computer programmer",
    "computer science",
    "computer security",
    "computer vision",
    "computer vision models",
    "concur",
    "concurrent pascal",
    "content management system",
    "cookies",
    "coral",
    "corba",
    "couchdb",
    "cronjobs",
    "cryptocurrency",
    "css",
    "cte",
    "cuda",
    "curl",
    "curry",
    "cypress",
    "dal",
    "dap",
    "dart",
    "dasl",
    "data engineer",
    "database",
    "database administration",
    "database architecture",
    "ddd",
    "debian",
    "decision-making",
    "deep learning",
    "delphi",
    "dhcp",
    "dibol",
    "director of engineering",
    "distributed system",
    "django",
    "dpdk",
    "drools",
    "drupal",
    "dtls",
    "dynamo db",
    "dynamodb",
    "ebpf",
    "ec2",
    "ecs",
    "eiffel",
    "elasticache",
    "elasticsearch",
    "elixir",
    "elt",
    "embedded software engineer",
    "erlang",
    "es6",
    "ext.js",
    "f#",
    "f-script",
    "ffmpeg",
    "firebase",
    "firewall",
    "flask",
    "flink",
    "flux",
    "forth",
    "fortran",
    "fril",
    "frink",
    "front end",
    "front-end",
    "frontend",
    "ftp",
    "full stack",
    "full-stack",
    "game developer",
    "gcp",
    "gcs",
    "git",
    "go",
    "golang",
    "google bigquery",
    "google cloud",
    "google cloud platform",
    "google cloud storage",
    "google tag manager",
    "gpu",
    "grape",
    "graphql",
    "gre",
    "groovy",
    "grunt",
    "gstreamer",
    "guava",
    "guice",
    "gulp",
    "hadoop",
    "haskell",
    "hbase",
    "hci",
    "hive",
    "hos",
    "html",
    "html5",
    "hypertalk",
    "ice",
    "ici",
    "icmp",
    "idl",
    "ike",
    "imagemagick",
    "information system",
    "information technology",
    "intercal",
    "io",
    "ios developer",
    "ip",
    "ipam",
    "ipsec",
    "ipv4/ipv6",
    "iso 26262",
    "jasmine",
    "jass",
    "java",
    "java developer",
    "java enterprise edition",
    "javascript",
    "javascript developer",
    "jboss",
    "jenkins",
    "jest",
    "jetson",
    "jetty",
    "jinja2",
    "joomla",
    "jquery",
    "js",
    "json",
    "kafka",
    "kinesis",
    "kotlin",
    "kubernetes",
    "labview",
    "lambda",
    "lamp",
    "laravel",
    "lava",
    "ldap",
    "li",
    "lightning",
    "linux",
    "linux kernel",
    "linux programming",
    "linux/unix",
    "lisp",
    "lua",
    "machine learning",
    "machine learning engineer",
    "macos",
    "maker language",
    "mandriva linux",
    "mantisbt",
    "maven",
    "memcache",
    "mercurial",
    "metaquotes language",
    "misra",
    "ml",
    "ml model",
    "mobx",
    "moment.js",
    "mongo",
    "mongo db",
    "mongodb",
    "mq",
    "ms-dos",
    "ms-windows",
    "msxml",
    "mulesoft developer",
    "multi-threaded",
    "mvc",
    "mvvm",
    "mysql",
    "nat",
    "natural language processing",
    "nemerle",
    "netcdf",
    "netty",
    "network and information security",
    "network engineer",
    "network programming",
    "networking",
    "nginx",
    "nlp",
    "node",
    "node.js",
    "nodejs",
    "non-relational databases",
    "nosql",
    "npm",
    "numpy",
    "oauth",
    "oauth2",
    "objective c",
    "objective-c",
    "ocaml",
    "odata",
    "oidc",
    "opencl",
    "opengl",
    "openid",
    "openssl",
    "operating systems",
    "optimizely",
    "oracle developer",
    "oracle sql developer",
    "orm",
    "os development",
    "ospf",
    "pandas",
    "parquet",
    "parsers",
    "pascal",
    "passport.js",
    "pentaho",
    "performance testing",
    "perl",
    "php",
    "php developer",
    "phpunit",
    "pl/i",
    "pl/sql",
    "play framework",
    "playwright",
    "postcss",
    "postgres",
    "postgresql",
    "postgressql",
    "postscript",
    "powershell",
    "presto",
    "problem-solving",
    "programmer analyst",
    "prolog",
    "protobuf",
    "puppeteer",
    "pyspark",
    "python",
    "python developer",
    "pytorch",
    "qa engineer",
    "r",
    "rabbit mq",
    "rabbitmq",
    "rails",
    "raspberry pi",
    "ravendb",
    "react",
    "react developer",
    "react native",
    "react.js",
    "reactjs",
    "reactnative",
    "redis",
    "redshift",
    "redux",
    "regex",
    "relational database",
    "responsive",
    "responsive design",
    "responsive development",
    "rest",
    "rest applications",
    "restapi",
    "restful api",
    "restlet",
    "rexx",
    "rhel",
    "robotics engineer",
    "rpg",
    "ruby",
    "ruby on rails",
    "rust",
    "s-plus",
    "s3",
    "salesforce developer",
    "saml",
    "sas",
    "scala",
    "scikit learn",
    "scikit-learn",
    "scikitlearn",
    "scipy",
    "search engine optimization",
    "security compliance",
    "sed",
    "selenium",
    "sensor calibration",
    "seo",
    "sftp",
    "sgml",
    "sharepoint developer",
    "shell script",
    "simula",
    "simulink",
    "sketch",
    "sklearn",
    "smalltalk",
    "smil",
    "snmp",
    "sns",
    "soap",
    "software developer",
    "software engineer",
    "solaris/aix",
    "sonarqube",
    "soql/sosl",
    "spark",
    "spl2",
    "splunk",
    "spring",
    "spring boot",
    "spring cloud",
    "spring mvc",
    "spss",
    "sql",
    "sql developer",
    "sqlalchemy",
    "sqlite",
    "sqs",
    "squirrel scripting",
    "ssh",
    "ssi",
    "ssl",
    "stata",
    "step functions",
    "storybook",
    "subversion",
    "suitescript",
    "svn",
    "swift",
    "symfony",
    "syslog",
    "tcl",
    "tcl/tk",
    "tcp",
    "tcp/ip",
    "tdd",
    "teamwork",
    "tensorflow",
    "teradata",
    "terraform",
    "tls",
    "tms",
    "tomcat",
    "travis",
    "travis ci",
    "travisci",
    "tsql",
    "tunneling",
    "typescript",
    "ubuntu",
    "udp",
    "ui",
    "ui developer",
    "ui/ux",
    "umbraco",
    "unified modeling language",
    "unity developer",
    "unix",
    "ux",
    "ux/ui",
    "vbscript",
    "vertica",
    "vertx",
    "vhdl",
    "visual basic",
    "visual foxpro",
    "visualforce",
    "vlan",
    "vpn",
    "vrfs",
    "vrrp",
    "vue",
    "vue.js",
    "vuejs",
    "wap",
    "wap/wml",
    "wcf",
    "web developer",
    "webkit",
    "webpack",
    "webrtc",
    "websockets",
    "wml",
    "wms",
    "wordpress",
    "wordpress developer",
    "wpf",
    "wsdl",
    "wsgi",
    "xaml",
    "xdp",
    "xhtml",
    "xml",
    "xpath",
    "xsl",
    "xslt",
    "yarn",
    "yui",
]
    
            export { swe_essentials }
            